### ISSUE TITLE
Add Check for Updates in Help menu

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray-editor#112]

**Comment by gdementen** [comment]
Use code from: https://github.com/liam2/larray/issues/330

**Comment by gdementen** [comment]
Use code from: https://github.com/liam2/larray/issues/330

**Comment by gdementen** [comment]
I doubt our users often use the Help menu, so they probably wouldn't use this much either.

**Comment by alixdamman** [comment]
> I doubt our users often use the Help menu, so they probably wouldn't use this much either.

You're right. I'll close this issue then.
