### ISSUE TITLE
compare: add tolerance when comparing arrays

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray-editor#131]
Add `threshold` option in `compare`: Two cells with difference in values < threshold are considered as equal.

Maybe linked to https://github.com/liam2/larray/issues/488

**Comment by gdementen** [comment]
Geert would like this to be high priority...

**Comment by alixdamman** [comment]
linked to https://github.com/larray-project/larray-editor/issues/131

**Comment by gdementen** [comment]
you link an issue to itself???
