### ISSUE TITLE
detect and display plots in tuple/list/arrays

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray-editor#135]
The editor detects return values of type "matplotlib.axes._subplots.AxesSubplot" and displays them, but some functions (notably Pandas "hist" method) or any plot with argument subplots=True produces an array of AxesSubplot and are thus not displayed. This is unfortunate and confusing for our users.

```python
>>> a = ndtest('sex=M,F;year=2000..2017')
>>> # this should work out of the box
>>> # a.plot(subplots=True)
>>> p = a.plot(subplots=True)
>>> p[0]
<matplotlib.axes._subplots.AxesSubplot at 0x20a9900ff98>
>>> type(p)
numpy.ndarray
>>> p.shape
(2,)
>>> type(p[0])
matplotlib.axes._subplots.AxesSubplot
```
We need to avoid examining all elements of arrays systematically, but I think checking the first element of arrays should be enough anyway.

**Comment by gdementen** [comment]
It also needs to work for arrays with ndim > 1. For example:
```python
a = ndrange('sex=M,F;nat=BE,FO;year=2000..2017')
a.plot(subplots=True)
```

**Comment by alixdamman** [comment]
ndim > 1:
```python
  a = ndtest('sex=M,F;nat=BE,FO;year=2000..2017')
  a.plot(subplots=True, layout=(2, 2))
```
