### ISSUE TITLE
when quitting the editor, cancel quits the editor

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray-editor#202]
(instead of returning back to it)
this is a grave bug, because it can lead to data loss

And there is a variant of the problem using this path:
quit->save->cancel. It should not quit the editor in that case!

**Comment by gdementen** [comment]
@alixdamman I wonder if we shouldn't target 0.32.1 with this? What do you think?

**Comment by alixdamman** [comment]
We can try to solve this for the 0.32.1 release.
