### ISSUE TITLE
unsaved changes indicator in viewer

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray-editor#21]
https://github.com/liam2/larray/issues/256

**Comment by alixdamman** [comment]
See also #22

**Comment by alixdamman** [comment]
Should I follow the behavior of MappingEditor._unsaved_modifications (set to True when arrays have added/deleted + **user clicked on Apply**) or should update the indicator as soon as the user changed the value of any cell (**before user clicked on Apply**)?

Second question:  MappingEditor._unsaved_modifications should be set to True as soon as the user changed the value of any cell (**before user clicked on Apply**)?

**Comment by gdementen** [comment]
Those two MUST be consistent, but yes _unsaved_modifications should ideally be True before apply.
