### ISSUE TITLE
some inplace operations not detected for array refresh

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray-editor#22]
https://github.com/liam2/larray/issues/259

**Comment by gdementen** [comment]
@alixdamman did you check this when doing #21? If so, this issue could be closed.

**Comment by alixdamman** [comment]
Problem is still there.

**Comment by gdementen** [comment]
This issue can mean two things: updating the window title with * (I think this was the original meaning of the issue) and refreshing the array widget data.

As of version 0.34.3 (and also in the compare_align branch after the "misc cleanups to console handling" commit) I got:

```python
arr = ndtest(5)
arr['a2'] = 10   # detected by array widget but not by title
arr['a2'] *= 10  # detected by neither (but losing focus -- or clicking next to the widget -- and regaining it, makes the array widget pick it up)
arr *= 2         # detected by both
```

**Comment by gdementen** [comment]
I assumed this issue was about the array widget refresh and #280 for window title
