### ISSUE TITLE
move axis names from header to viewport

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray-editor#31]
as a first step before to go to #14.

**Comment by gdementen** [comment]
this mean we need to adapt #28. But I do not think this would be a problem. We can add images (to show the presence of filters) to table cells, and have them clickable. Do you see any other potential problem?

**Comment by alixdamman** [comment]
That will change also how we want to manage drag and drop. I don't know if we can choose which cells are draggable and which not. But I think it's manageable (we need to reimplement dragEnterEvent, dragMoveEvent and dropEvent methods or something like that).
