### ISSUE TITLE
Implement undo/redo of individual value changes

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray-editor#32]
And remove "Apply"

**Comment by alixdamman** [comment]
Should we base our implementation of undo/redo on "Qt's Undo Framework" ( http://doc.qt.io/qt-5/qtwidgets-tools-undoframework-example.html ) or is it an overkill?

**Comment by gdementen** [comment]
I am unsure. Using that framework (*) **might** conflict with what I have in mind for the future: all methods available as commands, which you can chain and it builds a list of commands (effectively code) to create the current variable. To be able to view each step, we would need to either recompute or store them all. In my mind modification would be just a step like another.

(*) the part that seems in conflict is to have to provide an undo method. This will be impossible for many methods (e.g. all aggregates), so unsure it is worth it.

On the other hand storing a copy of the whole array for each cell changed would quickly become too wasteful. But recomputing shouldn't be a problem in most cases...

**Comment by alixdamman** [comment]
What I had in mind is a "limited" undo/redo at first. Something to get rid of that "Apply" button and the management of the "changes" dict. As usual, there is no clean/perfect way to do that. My hope is that using this framework would force us to implement something a bit more clean.

**Comment by gdementen** [comment]
Yes, but /**if**/ we determine that we will have to get rid of it later, we should rather not use it in the first place.

**Comment by gdementen** [comment]
In fact, the two could be complementary: undo/redo for each individual value change, and undoing other operations would simply remove the last command from the sequence and replay the sequence.

**Comment by alixdamman** [comment]
reminder: store old values instead of new values
