### ISSUE TITLE
File->New & Open fails when ipython console unavailable

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray-editor#35]
For example when view() is called from within an ipython console.

**Comment by gdementen** [comment]
would you mind tackling this for 0.25.2 instead?

**Comment by alixdamman** [comment]
This issue raises one question: 
aslarray(None) should return None, LArray([]) or what we do have now (arr.data = array(None, dtype=object)
)?

**Comment by gdementen** [comment]
I think what we have now is better. I could be convinced otherwise with a
strong use case for doing something else but it is more intuitive if
aslarray returns an LArray. This is also consistent with how np.asrray
works.
