### ISSUE TITLE
view, edit, compare not available by default in the console

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray-editor#44]
Regression in 0.25.

**Comment by alixdamman** [comment]
I guess the solution is simply to add 
```python
kernel.shell.run_cell('from larray-editor import *')
```
below
```python
kernel.shell.run_cell('from larray import *')
```

**Comment by gdementen** [comment]
yes, probably, but I wonder why it happens. `from larray import *` should already bring them in. And in fact, when in a normal python console, it does bring it in.

**Comment by alixdamman** [comment]
I made the change in editor.py file in site-packages directory. It seems to do the trick.
