### ISSUE TITLE
sync version with larray?

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray-editor#49]
Shouldn't we synchronize the version number with larray? This would simplify handling milestones. Here, it is not obvious that 0.1.1 issues would go with the 0.25.1 larray release.

The only downside I see to do this is if we ever want to release a new version which has changes only in the editor, which will make two (core) larray packages with the same code except for the version number. That seems odd but I can live with that for ease of maintenance.

**Comment by alixdamman** [comment]
In this case, we do not consider larray-editor as an independent project. But in the same time, I am not sure **if** and when larray-editor will become independent from larray. So why not.

**Comment by alixdamman** [comment]
Closed by PR #48
