### ISSUE TITLE
compare colors broken when filtering

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray-editor#66]
This is relatively high priority, in part because the bug is annoying for those using compare but also because fixing it would allow us to easily generalize the bg_value feature to view/edit and expose it to users. This could prove **very** useful for advanced visualisation. 
eg roll-your-own compare by stacking arrays and colouring them depending on whatever criteria you want (eg the relative difference, or the absolute difference or the cell which is maximum of several variants)

**Comment by alixdamman** [comment]
I would like to close PR #64 first.
