### ISSUE TITLE
Use QSettings to store if option "DontUseNativeDialog" is used when calling QFileDiaog.getOpenFileNames() in open()

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray-editor#78]
The file dialog opened by the `open` method crashes for some of our users. No exception is thrown. Only "Process finished with exit code 255" is displayed in console. After a rapid test, it seems that using the option `DontUseNativeDialog` works fine as a workaround but the displayed file dialog is a bit ugly.

**Comment by gdementen** [comment]
Not needed anymore. This was a conflict with "Dell Backup and Recovery" 1.8.x. 
I confirmed upgrading to 1.9.x fixes the issue. Uninstalling it should work too (but I have not tested that) and I do not know yet whether we use that application in house.

See http://en.community.dell.com/support-forums/software-os/f/3526/t/19634253
