### ISSUE TITLE
make the viewer more responsive when selecting/first showing a big array

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray-editor#93]
Currently it slows down to a crawl when working with big arrays.

The vmin/vmax computation could be the culprit. Being fast is more important than having perfect colors, so IF that is indeed the cause of the slowdown, we should use a sample, like for computing ndigits. But then the color code needs to be adapted to cope with having colorval > vmax OR, preferably updating vmin/vmax as we go, when loading more data.

**Comment by alixdamman** [comment]
Making viewer (editor) more responsive is not the purpose of implementing a "Data Buffer" as suggested in #33 ?

**Comment by gdementen** [comment]
The buffer _**for the visible data**_ is indeed a part of the picture. But here, **before** we visualize anything we work on the whole array to compute the min and max values, which for largish arrays is too slow. And I am unsure computing the min/max **only** on the current buffer is a good enough solution. Having a global min/max that is at first computed on the buffer and "enlarged" as necessary when we get more data might be a good solution OR do like we do for ndigits/scientific: compute it on a sample (pick a few hundred values from all over the array to minimize bias for "increasing" arrays)

**Comment by gdementen** [comment]
FWIW, here the slowdown I speak about is the time it takes between selecting the array in the list and the data being displayed. This issue is not about scrolling speed like #38.
