### ISSUE TITLE
add "save/load history" in File menu 

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray-editor#96]
And replace "Open/Save" by "Import/Export Arrays"?

**Comment by alixdamman** [comment]
@gdementen Implement this via magic function `%save` and `%load`, right?

**Comment by alixdamman** [comment]
Now I'm thinking of that, we could use this new functionality to write and load "test" scripts (but we still need a monkey to test the filters and menus ;) )

**Comment by alixdamman** [comment]
To be complete, opening/saving a session via the menu `File -> Open/Save` should run a command like `Session(<filepath>)`/`current_session.save(<filepath>)`

**Comment by gdementen** [comment]
> @gdementen Implement this via magic function %save and %load, right?

Yes, if that works (I have personally never used %load so I don't know what it does).

> To be complete, opening/saving a session via the menu File -> Open/Save should run a command like Session(<filepath>)/current_session.save(<filepath>)

Having all menus in the GUI available via commands is indeed the goal, but I don't think we can do that in the short term. For example, sessions currently do not know what file they come from, make it impossible to display the filename in the window title. All such little details will make it hard to only execute a command. But let us keep this in mind as a long term goal.

**Comment by alixdamman** [comment]
documentation for `load`: http://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-load
I'm not sure what the option `-n` does. 

I indeed wrote my second comment as reminder.

**Comment by alixdamman** [comment]
Reminder: 
- add tooltips
- use a QComboBox with previously saved/loaded scripts instead of a QLineEdit for the filepath.

**Comment by gdementen** [comment]
@alixdamman AARRRRRRGL. After some (too much than I should) more searching, I finally found how to set the input properly!!!! In our case, that is simply:
```python
self.eval_box.input_buffer = 'test'
```

**Comment by alixdamman** [comment]
@gdementen 

```python
self.eval_box.input_buffer = 'something'
```
inject something in the console, nothing more. It doesn't run the injected code. 
Also, using it means I can no longer call the magic function `%load` and use its options (like to load only some functions or lines).

I found the code of magic functions (in `IPython/core/magics/code.py` module, `CodeMagics` class). 
We could copy/paste but I'm not keen to do that (for the moment). 
I prefer to use `self.eval_box.input_buffer` to sum up what will be loaded (from which file, which lines, ...) and to ask them to push `Enter`.

**Comment by gdementen** [comment]
> inject something in the console, nothing more. It doesn't run the injected code.

I know, but it is already a lot more "understandable" than before.
